version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/localetrade
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always
