services:
  auth-service:
    build: ./backend/auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/localetrade

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - auth-service
    restart: always
