version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/localetrade
    depends_on:
      - mongo
    restart: always

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/localetrade
    depends_on:
      - mongo
    restart: always

  chat-service:
    build: ./chat-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/localetrade
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - chat-service
    restart: always
